spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: banghao.ch@gmail.com
    password: mharffkeggiunkes
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    addresses: localhost
    username: user
    password: 123456
    virtual-host: /
  security:
    jwt:
      key: wyb20030714
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


